flowchart LR
	AA(AA: 0)
	AA ---|3| ES
	AA ---|2| MO
	AA ---|2| XT
	AA ---|4| ZI
	AA ---|3| UH
	AG(AG: 13)
	AG ---|2| QJ
	AG ---|3| OR
	AG ---|3| TX
	ES(ES: 9)
	ES ---|2| SX
	MO(MO: 15)
	MO ---|2| ZI
	MO ---|2| UH
	MO ---|3| YB
	MO ---|2| OC
	OC(OC: 7)
	OC ---|2| UH
	OC ---|2| SX
	OC ---|2| ZI
	OC ---|3| VZ
	OR(OR: 6)
	OR ---|3| TX
	OR ---|2| QJ
	OR ---|4| ZI
	QJ(QJ: 11)
	QS(QS: 22)
	QS ---|2| YB
	RT(RT: 21)
	RT ---|2| XT
	SX(SX: 16)
	TX(TX: 19)
	TX ---|4| YB
	UH(UH: 17)
	UH ---|2| ZI
	VZ(VZ: 10)
	XT(XT: 18)
	YB(YB: 20)
	ZI(ZI: 5)