flowchart TD
        AA(AA: 0)
        AA---|1|DD
        AA---|2|JJ
        AA ---|1|BB
        BB(BB: 13)
        BB ---|1| CC
        CC(CC: 2)
        CC ---|1| DD
        DD(DD: 20)
        DD ---|1| EE
        EE(EE: 3)
        EE---|3|HH
        HH(HH: 22)
        JJ(JJ: 21)