%% To remove:
%% QB, QX - AA connects to ES with cost 3
%% PJ - UH connects to OC with cost 2
%% ZH - OC connects to MO with cost 2
%% TA, NE - OC connects to VZ with cost 3
%% BH, RU - OR connects to ZI with cost 3

flowchart LR
	AA(AA: 0)
	AA --- QZ
	AA --- UC
	AA --- OP
	AA --- EH
  AA ---|3| ES
	AG(AG: 13)
	AG --- NW
	AG --- GL
	AG --- SM
	AX(AX: 0)
	AX --- UH
	AX --- MO
	BY(BY: 0)
	BY --- UC
	BY --- ZI
	CB(CB: 0)
	CB --- MO
	CB --- XG
	EH(EH: 0)
	EH --- MO
	ES(ES: 9)
	ES --- FL
	FL(FL: 0)
	FL --- SX
	GE(GE: 0)
	GE --- YB
	GE --- OQ
	GL(GL: 0)
	GL --- QJ
	HB(HB: 0)
	HB --- OR
	HB --- QJ
	HM(HM: 0)
	HM --- TX
	HM --- QH
	IH(IH: 0)
	IH --- YB
	IH --- QS
	IZ(IZ: 0)
	IZ --- OC
	IZ --- SX
	JD(JD: 0)
	JD --- OR
	JD --- SM
	JR(JR: 0)
	JR --- ZI
	JR --- OC
	LF(LF: 0)
	LF --- ZI
	LF --- UH
	MG(MG: 0)
	MG --- TX
	MG --- NW
	MO(MO: 15)
	MO --- ON
  MO ---|2| OC
	NW(NW: 0)
	NX(NX: 0)
	NX --- UH
	NX --- OP
	OC(OC: 7)
  OC ---|2| UH
  OC ---|3| VZ
	ON(ON: 0)
	ON --- ZI
	OP(OP: 0)
	OQ(OQ: 0)
	OQ --- TX
	OR(OR: 6)
	OR --- QH
  OR ---|3| ZI
	PG(PG: 0)
	PG --- RT
	PG --- XT
	QH(QH: 0)
	QJ(QJ: 11)
	QS(QS: 22)
	QZ(QZ: 0)
	QZ --- XT
	RT(RT: 21)
	SM(SM: 0)
	SX(SX: 16)
	TX(TX: 19)
	UC(UC: 0)
	UH(UH: 17)
	VZ(VZ: 10)
	XG(XG: 0)
	XG --- YB
	XT(XT: 18)
	YB(YB: 20)
	ZH(ZH: 0)
	ZI(ZI: 5)

